### ISSUE TITLE
XDG_CONFIG_HOME variable

### ISSUE THREAD

**Issue by chekanov** [Dushistov/sdcv#99]
Hello,

 I'm not sure this variable XDG_CONFIG_HOME can be set. I do not see it in the source code. According to the description, this variable should point to the configuration files (if I want to redefine my $HOME)

**Comment by Dushistov** [comment]
Hi, @chekanov.

There is no mention of `XDG_` variables in source code, because of [glib](https://github.com/GNOME/glib) provides this functionality, and `sdcv` just uses functions from this library like `g_get_user_data_dir` and `g_get_user_config_dir` and so on.

You can find more details in this PR #59

**Comment by chekanov** [comment]
Thanks. I think it works now. when using this env variable.
